
export const sample_gems: any[] =
[
{
  id:'1',
  name: 'Vintage top',
  Time: '10-20',
  price: 10,
  favorite: false,
  origins: ['Roma'],
  stars: 4.5,
  imageUrl: 'assets/gem-1.jpg',
  tags: ['top', 'cute', 'vintage'],
},
{
  id:'2',
  name: 'Skirt',
  price: 20,
  Time: '20-30',
  favorite: true,
  origins: ['persia', 'middle east', 'china'],
  stars: 4.7,
  imageUrl: 'assets/gem-2.jpg',
  tags: ['skirt', 'vintage','yellow','black'],
},
{
  id:'3',
  name: 'Hearted scarf',
  price: 5,
  Time: '10-15',
  favorite: false,
  origins: ['germany', 'us'],
  stars: 3.5,
  imageUrl: 'assets/gem-3.jpg',
  tags: ['scrarf', 'vintage'],
},
{
  id:'4',
  name: 'Orange shirt',
  price: 2,
  Time: '15-20',
  favorite: true,
  origins: ['belgium', 'france'],
  stars: 3.3,
  imageUrl: 'assets/gem-4.jpg',
  tags: ['orange', 'shirt'],
},
{
  id:'5',
  name: 'classic shoes',
  price: 11,
  Time: '40-50',
  favorite: false,
  origins: ['india', 'asia'],
  stars: 3.0,
  imageUrl: 'assets/gem-5.jpg',
  tags: ['shoes', 'classic'],
},
{
  id:'6',
  name: 'Gray dress',
  price: 9,
  Time: '40-50',
  favorite: false,
  origins: ['italy'],
  stars: 4.0,
  imageUrl: 'assets/gem-6.jpg',
  tags: ['gray', 'dress', 'vintage'],
},
]

export const sample_tags: any[] = [
  { name: 'All', count: 6 },
  { name: 'skirt', count: 4 },
  { name: 'top', count: 2 },
  { name: 'dress', count: 3 },
  { name: 'gray', count: 1 },
  { name: 'vintage', count: 1 },
  { name: 'classic', count: 1 },
]

export const sample_users: any[] = [
  {
    name: "Rim Ouarrak",
    email: "ouri@gmail.com",
    password: "12345",
    address: "casa",
    isAdmin: true,
  },
  {
    name: "Rima Ouarrak",
    email: "rima@gmail.com",
    password: "12345",
    address: "rabat",
    isAdmin: false,
  },
];